server:
  port: 8000

spring:
  application:
    name: exchange-service
  datasource:
    url: jdbc:mysql://localhost:3306/exchange?allowPublicKeyRetrieval=true&useSSL=false
    username: exchange
    password: exchange
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

